#pragma once

#ifndef RESUMEF_INLINE_STATE
#if defined(__clang__) || defined(_MSC_VER)
#define RESUMEF_INLINE_STATE 1
#else
#define RESUMEF_INLINE_STATE 1
#endif	//defined(__clang__) || defined(_MSC_VER)
#endif	//RESUMEF_INLINE_STATE

#ifndef RESUMEF_DEBUG_COUNTER
/* #undef RESUMEF_DEBUG_COUNTER */
#endif	//RESUMEF_DEBUG_COUNTER

#ifndef _WITH_LOCK_FREE_Q_KEEP_REAL_SIZE
/* #undef _WITH_LOCK_FREE_Q_KEEP_REAL_SIZE */
#endif	//_WITH_LOCK_FREE_Q_KEEP_REAL_SIZE

#ifndef RESUMEF_DISABLE_MULT_THREAD
/* #undef RESUMEF_DISABLE_MULT_THREAD */
#endif	//RESUMEF_DISABLE_MULT_THREAD

/* #undef RESUMEF_USE_CUSTOM_SPINLOCK */
